language: node_js
node_js:
  - "10"
install:
  - yarn
before_deploy:
  - yarn build
deploy:
  provider: pages
  local_dir: build/
  target_branch: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
